language: node_js
node_js:
- 'stable'
before_install:
- openssl aes-256-cbc -K $encrypted_ac880c30010f_key -iv $encrypted_ac880c30010f_iv -in .deploy/key1.enc -out .deploy/key1 -d && chmod go-rwx .deploy/key1 || true
script:
- ./.deploy/deploy.sh
notifications:
  email: false
